defaults :
  - modulus_default
  - /arch/conv_fully_connected_cfg@arch.decoder
  - /arch/fno_cfg@arch.fno
  - scheduler: tf_exponential_lr
  - optimizer: adam
  - loss: sum
  - _self_

cuda_graphs: false
jit: false

custom:
  gradient_method: "fourier"
  ntrain: 1000
  ntest: 100
  experiment: "testing_vals"

arch:
  decoder:
    input_keys: [z, 32]
    output_keys: sol
    nr_layers: 1
    layer_size: 32

  fno:
    input_keys: coeff
    dimension: 2
    nr_fno_layers: 6
    fno_modes: 12
    padding: 9

scheduler:
  decay_rate: 0.95
  decay_steps: 1000

training:
  rec_results_freq : 500
  rec_validation_freq: 100
  max_steps : 10000
  summary_freq: 500

loss:
  weights:
    data: 0.00
    darcy: 1.0

batch_size:
  grid: 8
  validation: 8

network_dir: ${custom.experiment}/${custom.gradient_method}
#network_dir: "fourier-layers"


# @package _global_
#hydra:
#  sweeper:
#    +gradient_method: "fourier", "fdm", "exact"





